### ISSUE TITLE
Coupon field in ​/api​/orders​/coupons doesn't get the unlimited usage coupons.

### ISSUE THREAD

**Issue by mpragnarok** [libterty/ecommerce_backend#64]
Coupon field in ​/api​/orders​/coupons doesn't get the unlimited usage coupons.
controller name: getValidCoupons

**Comment by libterty** [comment]
@mpragnarok Please refer to the latest PR for fixing this issue. It's referring to the first settings of seeds data where unlimited_usage for shipping fee sets to null.
