### ISSUE TITLE
Item Pagination is empty on Page 3

### ISSUE THREAD

**Issue by mpragnarok** [libterty/ecommerce_backend#65]
Items should be divided by 10, therefore, only pages 1 and 2 should contain items. Page 3 shouldn't exist.

Potential cause: in getProducts controller, Index could be wrong. Instead of Index +1, it should be Index.

![image-20200212121703005](https://user-images.githubusercontent.com/9781206/74302723-72836880-4d92-11ea-8ef8-c69503127344.png)

**Comment by libterty** [comment]
@mpragnarok this is belongs to Frontend issue, please submit it on frontend page. The reason why it caused is because of insufficient seeds data. You can either re-config pagination settings in frontend or putting more data for the products into DB.
